repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        always_run: false
        pass_filenames: true
        types: [python]